# Generated by Django 2.2 on 2020-05-15 16:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=4)),
                ('name', models.CharField(max_length=64)),
                ('type', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pat_code', models.CharField(max_length=4)),
                ('pat_illness', models.CharField(max_length=64)),
                ('pat_doc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pats_of_doc', to='patient.Doc')),
            ],
        ),
    ]
