# Generated by Django 2.2 on 2020-05-25 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0002_remove_doc_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='all_docs',
            field=models.ManyToManyField(blank=True, related_name='all_docs', to='patient.Doc'),
        ),
        migrations.AddField(
            model_name='patient',
            name='pat_name',
            field=models.CharField(default='default', max_length=64),
        ),
    ]
