# Generated by Django 2.2 on 2020-06-01 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0003_auto_20200525_1612'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='pat_doc',
        ),
        migrations.AlterField(
            model_name='patient',
            name='all_docs',
            field=models.ManyToManyField(blank=True, related_name='al_docs', to='patient.Doc'),
        ),
    ]
