# Generated by Django 2.2 on 2020-06-01 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0004_auto_20200601_1236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='all_docs',
            field=models.ManyToManyField(blank=True, related_name='all_docs', to='patient.Doc'),
        ),
    ]
