# Generated by Django 2.2 on 2020-06-02 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0005_auto_20200602_0113'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='all_docs',
        ),
        migrations.AddField(
            model_name='doc',
            name='all_pats',
            field=models.ManyToManyField(blank=True, related_name='all_pats', to='patient.Patient'),
        ),
    ]
