# Generated by Django 2.2 on 2020-06-02 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0006_auto_20200602_1303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doc',
            name='all_pats',
            field=models.ManyToManyField(blank=True, related_name='all_pats_rel', to='patient.Patient'),
        ),
    ]
