# Generated by Django 2.2 on 2020-06-23 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('p_users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='regis',
            name='password',
        ),
    ]
