# Generated by Django 2.2 on 2020-06-24 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('p_users', '0002_remove_regis_password'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Regis',
        ),
    ]
